if not apex_collection.collection_exists('PO') then 

apex_collection.CREATE_COLLECTION ('PO');
 end if;

FOR a IN(
SELECT C001 ITEM_NAME,
C002 UOM,
C003 RATE,
C004 QTY
 FROM APEX_COLLECTIONS WHERE COLLECTION_NAME='PO'
)

LOOP 
INSERT INTO PO_DTL(ID,PO_NO,ITEM_NAME,RATE,QTY)
VALUES(ordersqq.NEXTVAL, :P17_PO_NO, a.ITEM_NAME,a.RATE,a.QTY);

END LOOP;

APEX_COLLECTION.TRUNCATE_COLLECTION ('PO');
